import type { NextPage } from "next";
import Head from "next/head";
import { useCallback } from "react";
import { Button } from "components/Button";

const Home: NextPage = () => {
  const signIn = useCallback(() => {}, []);
  console.log(process.env.NEXT_PUBLIC_ID);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Index page</h1>
      <Button onClick={signIn} text="サインイン" />
    </>
  );
};

export default Home;
