import Head from "next/head";
import { useCallback, useState, VFC } from "react";
import { signInWithPopup, GithubAuthProvider } from "firebase/auth";
import { auth, db } from "../firebase";
import { doc, setDoc, serverTimestamp } from "firebase/firestore";
import { FirebaseError } from "@firebase/util";
import Image from "next/image";
import { useRouter } from "next/router";
import { Loading } from "components/Loading";

const Home: VFC = () => {
  const provider = new GithubAuthProvider();
  const router = useRouter();

  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);

  const signIn = useCallback(async () => {
    try {
      setLoading(true);
      const result = await signInWithPopup(auth, provider);
      // ユーザーの情報
      const user = result.user;

      // ユーザー情報をFireStoreに保存
      await setDoc(doc(db, "users", user.uid), {
        name: user.displayName, // nullになってしまうが一旦保留
        iconURL: user.photoURL,
        isAdmin: false,
        createdAt: serverTimestamp(),
      });

      // コンテキストにユーザー情報を保存する

      await router.push("/home");
    } catch (error) {
      if (error instanceof FirebaseError) {
        setError(true);
      }
    } finally {
      setLoading(false);
    }
  }, []);

  if (loading) {
    return <Loading />;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-2 h-screen">
        <div className="self-center text-center">
          <div className="mb-5">
            <Image width={56} height={60} src="/logo.png" alt="" />
          </div>
          <h1 className="text-4xl mb-2 font-bold text-blue-600 stroke-current text-shadow">
            エンジビアの泉
          </h1>
          <p className="text-xl mb-10 font-bold text-blue-400 text-shadow">
            〜素晴らしきプログラミングマメ知識〜
          </p>
          <Image
            width={215}
            height={50}
            src="/sample-slack-button.png"
            alt="ログインボタン"
            onClick={signIn}
          />
        </div>
        <div className="bg-signin-img bg-cover bg-no-repeat bg-center"></div>
      </div>
    </>
  );
};

export default Home;
